generator:
  transformer:
    encoder:
      max_seq_len: 5000
      n_src_vocab: 100 # random number, will be reassigned in train.py
      d_word_vec: 512 # dimension of word vector
      n_layers: 6
      n_head: 8
      d_model: 512
      d_inner: 2048
      kernel_size: [9, 1]
      dropout: 0.2
    decoder:
      max_seq_len: 5000
      d_word_vec: 512
      n_layers: 6
      n_head: 8
      d_model: 512
      d_inner: 2048
      kernel_size: [9, 1]
      dropout: 0.2

  variance_predictor:
    input_size: 512
    filter_size: 512
    kernel_size: 3
    dropout: 0.5

  variance_embedding:
    pitch_quantization: "log" # support 'linear' or 'log', 'log' is allowed only if the pitch values are not normalized during preprocessing
    energy_quantization: "log" # support 'linear' or 'log', 'log' is allowed only if the energy values are not normalized during preprocessing
    n_bins: 256

  multi_speaker: False
  uv_threshold: 0.5

  postnet:
    postnet_embedding_dim: 512
    postnet_kernel_size: 5
    postnet_n_convolutions: 5

discriminator:
  segment_disc:
    pass

  detail_disc:
    pass

vocoder:
  model: "HiFi-GAN" # support 'HiFi-GAN', 'MelGAN'
  speaker: "universal" # support  'LJSpeech', 'universal'
